#                 ........        ..........              ............   .....................               
#               ...@@@^*...      ..,@@@@\*................,]]@@@@\]**.....]]]]/@@@@@@@@@@@]*...              
#               ..=@O@@O^*..     ..=@OO@@O\*@@@]]]`,]/@@@OOOOOOOOOO@@@\`@@OOOOOOOOOOOOO@@@@@`...             
#              ..*@OO@@Oo*..     ..=@OO@@@O`=@@OOOOOOOOOOOO@@@@@@@@@@Oooo@OOOO@@@@@@@@@@@OO/*...             
#              ..=@OO@@Oo*..     ..=@OO@@@O**o@@OO@@@@@@@OO@@@@@OOOOo/`*,O@@@@@@@@@OOOOo[`*....              
#             ..*@OOO@@O^..      ..=@OO@@@o*.*\O@@@@@@@@@OOO@@O/*........*,\O@@@@Oo`*........                
#             ..=@OO@@@O^..      .*@@OO@@@o*...*[[o/[[[O@OOO@@O^..      ....*@@@OO^..                        
#            ..*@@OO@@@O*..     ..*@@OO@@@o*..........*=@OOO@@O^..        ..=@O@OO^*.......                  
#            ..=@OOO@@@O*..     ..*@@OO@@@O*..      ..*@@OOO@@O^..       ..*@@O@@@@@@@@\]*....               
#            .*/@OOO@@Oo*..     ..*@OOO@@@O*..      ..*@@OO@@@O^..       ..=@OO@OOOOOOOO@@^*..               
#           ..*@@OOO@@Oo*.      ..=@OOOO@@O*..      ..=@OOO@@@O*..      ..*@OOOO@@@@@@@@@Oo*..               
#           ..*@@OOO@@O^*.      ..=@OOO@@@O*..      ..=@OOO@@@O*..     .../@OO@@@@@@@OOOo[*...               
#           ..*@@OOO@@O^..      ..=@OOO@@Oo*..      .*@@OOO@@@O*..     ..=@OO@@@OO/[***......                
#           ..*O@OOO@@O^*.      ..=@OO@@@O^..      ..*@@OOO@@@O*..    ..*@@OO@@Oo*.....                      
#            .*=@@OOO@@O*..    ..,@@O@@@O/*..      ..*@OOOO@@@o*..    ..,@OO@@@O^..........                  
#            ..*O@@OOO@@O`.....*/@OOO@@OO*..       ..*O@OOO@@Oo*.     .*@@OO@@OO`***]]]]`*.....              
#             ..,O@@@OOO@@@@@@@@OOO@@@@O`..         ..=@@OO@@O^*.    ..*@@O@@@@@@@OOOOOOO@@O]*...            
#             ...*\O@@@OOOOOOOOO@@@@@Oo*...         ..*\@@@@@O^..    ..*@OOOOOOOOOOOOOOOO@@@@@\`..           
#               ...*,OO@@@@@@@@@@@@Oo`....           ..*,OO@O/*..    ..*O@@@@@@@@@@@@@@@@@@@OO^*..           
#                 ....*[oOOOOOOOOo[*....              ....***....    ...*\OOOO@OOOOOOOooo[[[`*....           
#                    .....*****......                   .......       .....*******..............             
#                          ...                                              ....                             
#语言-可用的官方语言：i18n.zh_cn.yml、i18n.zh_tw
language: 'i18n.zh_cn.yml'
#食物设置##########################################################
food:
  hunger: 
    speed: 30   #每多少秒固定减少1点饥饿值
  rotten: 
    invenable: true   #是否打开背包食物腐烂机制
    guienable: true   #是否打开箱子GUI内食物腐烂机制
    invspeed: 30   #背包食物每多少秒计算一次新鲜度-1
    guispeed: 300   #箱子GUI内食物每多少秒计算一次新鲜度-1
#物品设置##########################################################
item:
  sawer: 
    enable: true   #是否开启内置物品掉落有标识的功能
  blowarrow:
    autoclear: 20   #吹箭、Sclerite卡在方块中多少秒自动清除
#玩家设置##########################################################
player:
  inventory: 
    enable: true   #是否开启背包限制功能
    lockSlots: 18  #初始锁定几格
  stats:
    autosave: 60   #自动保存玩家固有属性的周期
#世界设置##########################################################
world:
  darkness: 
    warnTime: 3   #在亮度为0的黑暗中停留几秒会警告
    attackTime: 7   #在亮度为0的黑暗中停留几秒会攻击
    darkDamage: 10   #在亮度为0的黑暗中停留attack秒后攻击的伤害
    sanWarn: -5   #在亮度为0的黑暗中停留warn秒后每秒影响的理智值
    sanAttack: -10   #在亮度为0的黑暗中停留attack秒后每秒影响的理智值
    carrotEffect: 10  #吃萝卜可以暂时免疫黑暗的秒数（金萝卜*5）
  season:
    spring: 30   #春天大约多少天（会有10天的随机浮动）
    autumn: 30   #秋天大约多少天（会有10天的随机浮动）
    summer: 20   #夏天大约多少天（会有10天的随机浮动）
    winter: 20   #冬天大约多少天（会有10天的随机浮动）
#方块设置##########################################################
block:
  fresh: 60   #方块保存与读取的CD
disableWorlds:   #不启用插件的世界
- world_nether

# 数据保存设置
# name -> 玩家名 & yml (v1)
# nameV2 -> 玩家名 & yml (v2)
# uuid -> UUID & yml
# name-bin -> 玩家名 & 二进制
# uuid-bin -> uuid & 二进制
saving: "name"
# 开启DEBUG模式
# 能获得最详细的执行情况
# 但是. 前提是你的磁盘撑得住
debug: false
#区域设置##########################################################
ignoreResidences:
# 插件在哪些领地中失效（RESIDENCE前置）
- residence1
- residence2
